username: "Aviv"
password: "1234"
conpany: ".ERICOM SOFTWARE LTD"
Attendance:
  "22":
    "04":
      "03":
        start: "0600"
        end : "1700"
      "04":
        start: "0900"
        end : "1800"
      "05":
        start: "0900"
        end : "1800"
      "06":
        start: "0600"
        end : "1730"
      "07":
        start: "0800"
        end : "1700"
      "10":
        start: "0900"
        end : "1800"
      "11":
        start: "0700"
        end : "1600"
      "12":
        start: "0600"
        end : "1500"
      "13":
        start: "0600"
        end : "1600"
      "14":
        start: "0600"
        end : "1500"
      "17":
        start: "0730"
        end : "1600"
      "18":
        start: "0730"
        end : "1600"
      "19":
        start: "0630"
        end : "1600"
      "20":
        start: "0630"
        end : "1530"
      "21":
        start: "1700"
        end : "2100"
      "24":
        start: "0900"
        end : "1800"
      "25":
        start: "0630"
        end : "1530"
      "26":
        start: "0700"
        end : "1600"
      "27":
        start: "0700"
        end : "1700"
      "28":
        start: "0800"
        end : "1700"

    "05":
      "01":
        start: "0700"
        end : "1800"
      "02":
        start: "0800"
        end : "1730"
      "03":
        start: "0700"
        end : "1730"
 

