username: "Aviv"
password: "1234"
conpany: ".ERICOM SOFTWARE LTD"
Attendance:
  "22":
    "04":
      "01":
        start: "0900"
        end : "1800"
      "02":
        start: "0900"
        end : "1800"
      "03":
        start: "0900"
        end : "1800"
      "04":
        start: "0900"
        end : "1800"
      "05":
        start: "0900"
        end : "1800"
      "06":
        start: "0900"
        end : "1800"
      "07":
        start: "0900"
        end : "1800"
      "08":
        start: "0900"
        end : "1800"
      "09":
        start: "0900"
        end : "1800"
      "10":
        start: "0900"
        end : "1800"
