username: "Aviv"
password: "1234"
conpany: "Ericom"
Attendance:
  "22":
    "4":
      "1":
        start: "09:00"
        end : "18:00"
      "2":
        start: "09:00"
        end : "18:00"
      "3":
        start: "09:00"
        end : "18:00"
      "4":
        start: "09:00"
        end : "18:00"
      "5":
        start: "09:00"
        end : "18:00"
      "6":
        start: "09:00"
        end : "18:00"
      "7":
        start: "09:00"
        end : "18:00"
      "8":
        start: "09:00"
        end : "18:00"
      "9":
        start: "09:00"
        end : "18:00"
      "10":
        start: "09:00"
        end : "18:00"
